# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

include: "rules/common.smk"
include: "rules/conda_info.smk"

SIMULATIONS = ["A", "B"]

rule all:
    input:
        expand("results/{simulation}.txt", simulation=SIMULATIONS)
